services:
  mongodb:
    image: mongo:7.0
    container_name: smart-task-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: todoapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - smart-task-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-task-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=todoapp
    depends_on:
      - mongodb
    networks:
      - smart-task-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart-task-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - smart-task-network

volumes:
  mongodb_data:

networks:
  smart-task-network:
    driver: bridge
