services:
  mongodb:
    image: mongo:7.0
    container_name: smart-task-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: todoapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - smart-task-network

  ollama:
    image: ollama/ollama:latest
    container_name: smart-task-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - smart-task-network
    environment:
      - OLLAMA_ORIGINS=*

volumes:
  mongodb_data:
  ollama_data:

networks:
  smart-task-network:
    driver: bridge
