services:
  mongodb:
    image: mongo:7.0
    container_name: smart-task-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: todoapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - smart-task-network

  redis:
    image: redis:7.2-alpine
    container_name: smart-task-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart-task-network
    command: redis-server --appendonly yes

volumes:
  mongodb_data:
  redis_data:

networks:
  smart-task-network:
    driver: bridge
